export const FETCH_HELLO_WORLD_REQUESTED = 'FETCH_HELLO_WORLD_REQUESTED';
export const FETCH_HELLO_WORLD_SUCCEEDED = 'FETCH_HELLO_WORLD_SUCCEEDED';
export const FETCH_HELLO_WORLD_FAILED = 'FETCH_HELLO_WORLD_FAILED';
